# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Erigo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya', '~> 13.0.1'
  pod 'IQKeyboardManager'
  pod 'YPImagePicker'
  pod 'Kingfisher', '7.6.2'
  pod 'ProgressHUD'
  # pod 'AppsFlyerFramework', '6.14.4'
  pod 'RMStore'

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        end
    end
end